### ISSUE TITLE
Don't add nodejs repo on buster

### ISSUE THREAD

**Issue by bjoernricks** [martinboller/Greenbone-GVM10#2]
https://github.com/martinboller/Greenbone-GVM10/blob/47a6e09f0c3f9a8d99f04af4e78ed10fb4826170/install-vuln-scan10.0.1.sh#L25

You should not add the nodejs repo when using debian buster. Buster already contains a even newer version https://packages.debian.org/buster/nodejs

**Comment by martinboller** [comment]
Thanks Björn - Decided 2day to create this for GVM SCE 20.08 so this is obsolete :)
